# Generated by Django 2.2.10 on 2021-02-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210203_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='website',
            field=models.URLField(max_length=128, null=True),
        ),
    ]
