# Generated by Django 2.2.10 on 2021-04-06 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_art_like_count'),
        ('user', '0007_auto_20210406_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField()),
                ('status', models.PositiveIntegerField(choices=[(1, '대기'), (2, '실패'), (3, '성공'), (4, '배송 준비중'), (5, '배송 중'), (6, '배송 완료'), (7, '환불'), (8, '환불 완료'), (9, '구매 확정')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('art', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='art.Art')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Artist')),
                ('userinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserInfo')),
            ],
        ),
    ]
