# Generated by Django 2.2.10 on 2021-04-12 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210412_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_address',
            field=models.CharField(
                default='recipient_address', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(default='default', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(
                default='recipient_phone', max_length=16, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
