# Generated by Django 2.2.10 on 2021-04-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210412_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '취소'), (1, '대기'), (2, '실패'), (3, '성공'), (4, '배송 준비중'), (5, '배송 중'), (6, '배송 완료'), (7, '환불'), (8, '환불 완료'), (9, '구매 확정')], default=1),
        ),
    ]
