# Generated by Django 2.2.10 on 2021-04-16 07:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210415_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
