# Generated by Django 2.2.10 on 2021-05-07 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_order_delivery_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transacted_at', models.DateTimeField()),
                ('transaction_id', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=32)),
                ('amount', models.IntegerField()),
                ('pay_method', models.CharField(max_length=32)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Order')),
            ],
        ),
    ]
