# Generated by Django 2.2.10 on 2021-06-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210531_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='website',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
