# Generated by Django 2.2.10 on 2021-02-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='bucket',
            field=models.CharField(choices=[('assets', '기본 버킷')], default='assets', max_length=8),
        ),
        migrations.AlterField(
            model_name='file',
            name='content_type',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
