# Generated by Django 2.2.10 on 2021-02-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_art_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='name',
            field=models.CharField(default='a', max_length=128),
            preserve_default=False,
        ),
    ]
