# Generated by Django 2.2.10 on 2021-04-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_auto_20210310_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
