# Generated by Django 2.2.10 on 2021-05-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_art_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='medium',
            field=models.PositiveIntegerField(choices=[(0, '회화'), (1, '조각'), (2, '사진'), (3, '소묘'), (4, '판화'), (5, '종이'), (6, '섬유'), (7, '기타 매체')], default=0),
        ),
        migrations.AlterField(
            model_name='style',
            name='medium',
            field=models.PositiveIntegerField(choices=[(0, '회화'), (1, '조각'), (2, '사진'), (3, '소묘'), (4, '판화'), (5, '종이'), (6, '섬유'), (7, '기타 매체')], default=0),
        ),
        migrations.AlterField(
            model_name='technique',
            name='medium',
            field=models.PositiveIntegerField(choices=[(0, '회화'), (1, '조각'), (2, '사진'), (3, '소묘'), (4, '판화'), (5, '종이'), (6, '섬유'), (7, '기타 매체')], default=0),
        ),
        migrations.AlterField(
            model_name='theme',
            name='medium',
            field=models.PositiveIntegerField(choices=[(0, '회화'), (1, '조각'), (2, '사진'), (3, '소묘'), (4, '판화'), (5, '종이'), (6, '섬유'), (7, '기타 매체')], default=0),
        ),
    ]
