# Generated by Django 2.2.10 on 2021-05-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_auto_20210516_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='art',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
